### PR TITLE
Cwl browse

### PR DESCRIPTION
**Pull request by ThilinaManamgoda**
This testing .So please tell me this process is correct or wrong

### CODE REVIEW

**Comment by stain** [comment]
Yes, this looks OK - except you are committing an extra `Readme.md~` - Emacs backup file?

Now could you try to remove that locally with `git rm` and `git commit`, then `git push` again - it should update this pull request.

**Comment by ThilinaManamgoda** [comment]
How about now

**Comment by stain** [comment]
Thanks!

**Comment by stain** [comment]
Remember to pull as I also merged latest `master`

**Pull request merged**
