### PR TITLE
CWL

### PR DESCRIPTION
**Pull request by ThilinaManamgoda**
i have merged the taverna-3 branch to master branch

### CODE REVIEW

**Comment by galejwnaylor** [comment]
In incubator-taverna-common-activities/taverna-cwl-activity/src/main/java/org/apache/taverna/cwl/ is it possible to rename CwlDumyActivity.java to CwlDummyActivity.java?

**Comment by stain** [comment]
Thanks!

Some licensing things.. (sorry):

You add [cwl-logo-header.png](https://github.com/ThilinaManamgoda/incubator-taverna-common-activities/blob/master/taverna-cwl-activity-ui/src/main/resources/Icons/cwl-logo-header.png)  - we talked about this coming from [commonwl.org repository](https://github.com/common-workflow-language/common-workflow-language/blob/master/site/CWL-Logo-Header.png) which is [now Apache licensed](https://github.com/common-workflow-language/common-workflow-language/blob/master/LICENSE.txt)

This simplifies things for us (compared to Creative Commons), but we still need to respect these elements of [Clause 4](https://www.apache.org/licenses/LICENSE-2.0.html#redistribution):

> (b) You must cause any modified files to carry prominent notices stating that You changed the files; and
> 
> (c) You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and

Clause a) is obvious as we are also Apache 2.0-licensed. As there is no `NOTICE` file in https://github.com/common-workflow-language/common-workflow-language we don't need to comply with clause d).

I think you have scaled and cropped the image, so we need to add the b) notice. Obviously this is a bit tricky in PNG - PNG metadata is not 'prominent', so perhaps adding a cwl-logo-header.txt would be easiest? 

In `cwl-logo-header.txt` we can also for c) copy the attribution from the [CWL contributor list](https://github.com/common-workflow-language/common-workflow-language#individual-contributors) - we don't know which of these have contributed to the logo itself, but we can ask @tetron and @mr-c.

So @ThilinaManamgoda - would you be able to add such a text file to neighbour the PNG? Something like:

> cwl-logo-header.png adapted by Thilina Manamgoda, original from
> https://github.com/common-workflow-language/common-workflow-language/blob/master/site/CWL-Logo-Header.png
> which was contributed by 
> Peter Amstutz, 
> John Doe
> etc.  (we can shrink the big list once we get info about who made the logo)

Also could you remove the [potatoman exampleIcon.png](https://github.com/ThilinaManamgoda/incubator-taverna-common-activities/blob/master/taverna-cwl-activity-ui/src/main/resources/exampleIcon.png) as we now believe we do not have permission to redistribute this :-(

**Comment by mr-c** [comment]
The logo is under the following license: https://github.com/common-workflow-language/logo/blob/master/LICENSE.md

The logo was done as a work for hire by @stefanmalacu

**Comment by stain** [comment]
Thanks, @mr-c! But does this not mean that https://github.com/common-workflow-language/common-workflow-language/blob/master/site/CWL-Logo-Header.png is a redistribution is a violation of both those licenses and also misleading as its [top-level repository LICENSE](https://github.com/common-workflow-language/common-workflow-language/blob/master/LICENSE.txt) claim it is Apache license?

**Comment by mr-c** [comment]
@stain Indeed; I've created a pull request to clarify the situation. https://github.com/common-workflow-language/common-workflow-language/pull/288

**Comment by stain** [comment]
@ThilinaManamgoda if the https://github.com/common-workflow-language/common-workflow-language/blob/master/site/CWL-Logo-Header.png logo is truly still under LGPL and CC-BY-SA-3.0 (which I think @mr-c would need to clarify), then we can't redistribute your shrunk PNG version, as it then [needs to be unmodified](http://apache.org/legal/resolved.html#cc-sa).

Of course you would be free to contribute the modified shrunk version back to  https://github.com/common-workflow-language/logo and then we use that binary "unmodified". But still being under CC-BY-SA 3.0  it means you would need to modify this top-level `LICENSE` and `README`, e.g. as in https://github.com/apache/incubator-taverna-language/blob/master/LICENSE#L271

**Comment by stain** [comment]
Thanks, @mr-c. Perhaps the simplest then is to drop the logo again.. unless @ThilinaManamgoda would like to have a go at adding those `LICENSE` and `README` modificatoins?

**Comment by ThilinaManamgoda** [comment]
[Example.png](https://github.com/ThilinaManamgoda/incubator-taverna-common-activities/blob/master/taverna-cwl-activity-ui/src/main/resources/exampleIcon.png) is deleted.
I will try to add those licenses

**Pull request merged**
