### PR TITLE
dummy Docker activity

### PR DESCRIPTION
**Pull request by NadeeshDilanga**
This is a testing. Suddenly remembered that I didn't do this. Please tell me if I'm doing this wrong.

### CODE REVIEW

**Comment by stain** [comment]
It looks good - but I think we'll put it the pull requests towards the `docker` branch rather than `master` so this doesn't get half-way into a release. 

Could you change/reissue the pull request against that branch?

**Comment by stain** [comment]
@NadeeshDilanga if this pull request is now superseded by the merged #5, could you close this? Thanks!

**Comment by stain** [comment]
@NadeeshDilanga - it's best to have one branch per pull request, otherwise all the open pull requests move ahead at the same pace. 

Both this and #8 are fed from your `docker` branch, but this pull request should be closed as it asks to be merged into the Apache-side `master` instead of `docker`.

**Comment by NadeeshDilanga** [comment]
Hi Stian,
I was sending pull requests on for different phases. Each pull request has
the diff of the particular phase. Means, I have 5 pull requests, and my
whole code is combination of all 5 pull requests.

Can you please explain on sending each pull request from different branches
? You want 5 pull requests, 1st one from branch_1, 2nd one from branch_2
like wise ? If that is the case, won't it going to create lot of branches
end of day. In that sense, shall I keep the code in my repo and at the time
of GSoC completion, I will send one pull request that has the entire
implementation ?

**Comment by stain** [comment]
Hi, I'm OK with incremental pull requests, but the problem is that if you have multiple open pull requests from the same branch, then they are effectively the same pull requests and I wouldn't know which commit to review..  

When you have a sizeable code, as in #8, then open a new pull request from a new "feature" branch on your GitHub repository.  If we need to fix some small details for that pull requests, then you can fix it on that branch separately. We can then review this and merge it - while you keep working on something else.

For your continued work, you can then do that on a new feature branch, so you don't affect the pull request and we can review it without having a moving target.  You might need to occasionally merge your older feature branches into the newer feature branches.

Obviously here you are not doing independent patches, you are building on your own work, and so you would base such new feature branches from your own feature branch, rather than the Apache branch (which might lag behind).

This is an area where GitHub pull requests start being difficult, because your newer pull request will build on the old one, so you can just say "Depends on #3") so they can be reviewed in order. But even if we do merge the later PR, then GitHub will figure out both PRs have been merged.

Your feature branches shouldn't be called "branch_1" etc, but rather refer either to a JIRA issue number or to the main fixed/new feature, e.g. `dockerjava` or `certificate-path`.

GitHub will tell you "You can safely delete this branch" once a pull request is accepted, just click the "Delete" branch there, and do `git branch -d` locally after pulling the new upstream.

No, I would not prefer a "One PR at the end of GSOC" approach :)  Let's continue with small PRs so they are easy to review :)

**Pull request closed without merging**
